### ISSUE TITLE
Time zone issue

### ISSUE THREAD

**Issue by lionslair** [bremor/bureau_of_meteorology#226] opened 2024-06-23 23:33 UTC
Not really a big but saw this in my logs so passing it on as FYI

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/bureau_of_meteorology/sensor.py:340
integration: Bureau of Meteorology (documentation, issues)
First occurred: June 22, 2024 at 7:43:17 AM (572 occurrences)
Last logged: 7:27:40 AM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 411, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
    update_callback()
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 203, in _update_callback
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 340, in state
    utc = timezone.utc
          ^^^^^^^^
NameError: name 'timezone' is not defined

**Comment by grantclem** [comment] 2024-06-24 00:14
+1

**Comment by MickW69** [comment] 2024-07-07 09:38
Log details (ERROR)
This error originated from a custom integration.
Logger: homeassistant
Source: custom_components/bureau_of_meteorology/sensor.py:340
integration: Bureau of Meteorology ([documentation](https://github.com/bremor/bureau_of_meteorology), [issues](https://github.com/bremor/bureau_of_meteorology/issues))
First occurred: 8:16:37 AM (136 occurrences)
Last logged: 7:35:12 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 411, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
    update_callback()
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 203, in _update_callback
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 340, in state
    utc = timezone.utc
          ^^^^^^^^
NameError: name 'timezone' is not defined

**Comment by GracieSW584** [comment] 2024-07-23 15:08
+1

**Comment by mitch-1211** [comment] 2024-07-24 02:09
Also see #231 (apologies for duplicate!)

**Comment by Makin-Things** [comment] 2024-07-24 10:04
Duplicate of #231

**Closed as completed by Makin-Things** 2024-07-24 10:04 UTC
