### ISSUE TITLE
The bureau_of_meteorology custom integration is using deprecated weather forecast

### ISSUE THREAD

**Issue by joshk169** [bremor/bureau_of_meteorology#203] opened 2023-12-09 05:24 UTC
This stops working in version 2024.3.0. Please address before upgrading.

The custom integration bureau_of_meteorology implements the forecast property or sets self._attr_forecast in a subclass of WeatherEntity.

Please create a bug report at https://github.com/bremor/bureau_of_meteorology/issues.

Once an updated version of bureau_of_meteorology is available, install it and restart Home Assistant to fix this issue.

**Comment by juhurus** [comment] 2023-12-09 14:18
yep, got the same message today.

**Comment by Roger-The-Paradox** [comment] 2023-12-10 20:35
This is a duplicae of #189 

Does nobody check before creating a new one?

**Comment by Makin-Things** [comment] 2024-07-24 10:06
Duplicate of #189

**Closed as completed by Makin-Things** 2024-07-24 10:06 UTC
