### ISSUE TITLE
Sensors report as Unavailable, and error log shows "Cannot connect..."

### ISSUE THREAD

**Issue by kenrob2** [bremor/bureau_of_meteorology#118] opened 2022-05-14 12:28 UTC
G'day,
The integration was previously working without incident.
 
Now all the sensors are reporting unavailable.  I had tried to update to 1.12, that failed.  I have now updated to 1.15, apparently successfully, but sensors are still unavailable.  The last line in the error log reads:
"aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.weather.bom.gov.au:443 ssl:default [Try again]"

I don't know where to look for more details.
 
-- 
Regards,
Ken
[BoM_ErrorLog.txt](https://github.com/bremor/bureau_of_meteorology/files/8692913/BoM_ErrorLog.txt)

**Comment by Makin-Things** [comment] 2022-05-16 10:18
This sounds like when the integration started that there was no internet connectivity. Possibly a duplicate of #113

**Comment by kenrob2** [comment] 2022-05-16 13:08
Thanks for your comment.  
I'd agree that a lack on connectivity could result in the symptom I'm seeing, but I'd expect such a lack of connectivity to affect some of the other ~20 integrations, a number of which are collecting cloud sourced data.  (Although some of those are behaving oddly/intermittently, AirVisual, Accuweather, NSW Fuel prices.)
I've just noticed release 1.1.7 and updated & restarted, the sensors are still unavailable.

purcell-lab mentioned in issue #113 that "If I manually restart the component after the Internet is up everything is fine."  How do you "restart the component"?

**Comment by purcell-lab** [comment] 2022-06-15 22:46
You can **Reload** from the 3dots box, but I suspect this should be resolved with the resolution of #113 
![image](https://user-images.githubusercontent.com/79175134/173954712-cedec89e-22d4-4f6b-bb2a-7e88f5ebbbd2.png)

**Comment by Makin-Things** [comment] 2022-07-01 04:42
Assuming fixed.

**Closed as completed by Makin-Things** 2022-07-01 04:42 UTC
