### ISSUE TITLE
Sensor Request - Pressure

### ISSUE THREAD

**Issue by philhanic** [bremor/bureau_of_meteorology#51] opened 2020-12-03 08:03 UTC
Hi, can you please include a sensor for atmospheric pressure. Thanks!

**Comment by bremor** [comment] 2020-12-04 04:26
Hey mate. I plan to add pressure and delta_t at some stage, it’s just a bit complex because this API does not offer those values so I would have to pull them from BoM FTP instead. BoM FTP pulls a ~350kB file every 30 mins which is not great so I would have to make it opt-in via the config flow process.

It’s coming but you will have to wait a couple of weeks

**Comment by theOzzieRat** [comment] 2020-12-05 01:57
It's worse than that. The files for observations on the ftp site (IDx60920.xml) vary in size depending on the state you are in. NSW is 530kB. They are also updated every 10 minutes.

**Comment by philhanic** [comment] 2020-12-06 06:36
Thanks for your reply. Love your work!

**Comment by Canonfodda** [comment] 2020-12-08 05:49
Absolutely awesome work. Atmospheric pressure is also a request for me as I'm a sailer. It seems troublesome, unfortunately.

**Comment by bremor** [comment] 2020-12-26 20:26
Closing since it's a duplicate of #19

**Closed as completed by bremor** 2020-12-26 20:26 UTC
